{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "08f6abe1-e61f-4c02-a0ca-c15548418413",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "#import seaborn as sns\n",
    "import requests \n",
    "import json\n",
    "from shapely.geometry import Point\n",
    "import geopandas as gpd\n",
    "import ast"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c4005852-9a22-4c98-a73f-61473c4aabf1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(     Unnamed: 0   id                          name  light number  \\\n",
       " 0             0    1         1a - Puerta del Sol A      3     1a   \n",
       " 1             1    2         1b - Puerta del Sol B      3     1b   \n",
       " 2             2    3               2 - Miguel Moya      3      2   \n",
       " 3             3    4        3 - Plaza Conde Suchil      2      3   \n",
       " 4             4    5                  4 - Malasaña      1      4   \n",
       " ..          ...  ...                           ...    ...    ...   \n",
       " 259         259  265                    257 - INEF      0    257   \n",
       " 260         260  266  258 - Ciudad Universitaria 1      2    258   \n",
       " 261         261  267  259 - Ciudad Universitaria 2      2    259   \n",
       " 262         262  268       260 - Facultad Biología      2    260   \n",
       " 263         263  269        261 - Facultad Derecho      2    261   \n",
       " \n",
       "                                                address  activate  \\\n",
       " 0                                  Puerta del Sol nº 1         1   \n",
       " 1                                  Puerta del Sol nº 1         1   \n",
       " 2                               Calle Miguel Moya nº 1         1   \n",
       " 3             Plaza del Conde del Valle de Súchil nº 3         1   \n",
       " 4                          Calle Manuela Malasaña nº 5         1   \n",
       " ..                                                 ...       ...   \n",
       " 259  Avenida Juan de Herrera frente a la calle Paul...         1   \n",
       " 260  Avenida de la Complutense (Metro Ciudad Univer...         1   \n",
       " 261  Avenida de la Complutense (Metro Ciudad Univer...         1   \n",
       " 262          Calle José Antonio Novais frente al nº 12         1   \n",
       " 263                          Avenida Complutense nº 23         1   \n",
       " \n",
       "      no_available  total_bases  dock_bikes  free_bases  reservations_count  \\\n",
       " 0               1           30           0           0                   0   \n",
       " 1               1           30           0           0                   0   \n",
       " 2               1           24           0           0                   0   \n",
       " 3               0           18           9           9                   0   \n",
       " 4               0           24          23           1                   0   \n",
       " ..            ...          ...         ...         ...                 ...   \n",
       " 259             0           24           3          19                   0   \n",
       " 260             0           24           9          14                   0   \n",
       " 261             0           24          12          10                   0   \n",
       " 262             0           24          12          10                   0   \n",
       " 263             0           24           8          16                   0   \n",
       " \n",
       "     geometry.type                     geometry.coordinates  \n",
       " 0           Point                 [-3.7018341, 40.4172137]  \n",
       " 1           Point  [-3.701602938060457, 40.41731271011562]  \n",
       " 2           Point                 [-3.7058415, 40.4205886]  \n",
       " 3           Point                 [-3.7069171, 40.4302937]  \n",
       " 4           Point                 [-3.7025875, 40.4285524]  \n",
       " ..            ...                                      ...  \n",
       " 259         Point                     [-3.72997, 40.43896]  \n",
       " 260         Point                     [-3.72699, 40.44375]  \n",
       " 261         Point                     [-3.72693, 40.44342]  \n",
       " 262         Point                 [-3.7272945, 40.4483322]  \n",
       " 263         Point                     [-3.72937, 40.45109]  \n",
       " \n",
       " [264 rows x 14 columns],\n",
       "                                                    @id  \\\n",
       " 0    https://datos.madrid.es/egob/catalogo/tipo/ent...   \n",
       " 1    https://datos.madrid.es/egob/catalogo/tipo/ent...   \n",
       " 2    https://datos.madrid.es/egob/catalogo/tipo/ent...   \n",
       " 3    https://datos.madrid.es/egob/catalogo/tipo/ent...   \n",
       " 4    https://datos.madrid.es/egob/catalogo/tipo/ent...   \n",
       " ..                                                 ...   \n",
       " 499  https://datos.madrid.es/egob/catalogo/tipo/ent...   \n",
       " 500  https://datos.madrid.es/egob/catalogo/tipo/ent...   \n",
       " 501  https://datos.madrid.es/egob/catalogo/tipo/ent...   \n",
       " 502  https://datos.madrid.es/egob/catalogo/tipo/ent...   \n",
       " 503  https://datos.madrid.es/egob/catalogo/tipo/ent...   \n",
       " \n",
       "                                                  @type        id  \\\n",
       " 0    https://datos.madrid.es/egob/kos/entidadesYorg...  11353987   \n",
       " 1    https://datos.madrid.es/egob/kos/entidadesYorg...   6344681   \n",
       " 2    https://datos.madrid.es/egob/kos/entidadesYorg...  11350944   \n",
       " 3    https://datos.madrid.es/egob/kos/entidadesYorg...  11350990   \n",
       " 4    https://datos.madrid.es/egob/kos/entidadesYorg...  11350948   \n",
       " ..                                                 ...       ...   \n",
       " 499  https://datos.madrid.es/egob/kos/entidadesYorg...   6280408   \n",
       " 500  https://datos.madrid.es/egob/kos/entidadesYorg...     38383   \n",
       " 501  https://datos.madrid.es/egob/kos/entidadesYorg...  10967962   \n",
       " 502  https://datos.madrid.es/egob/kos/entidadesYorg...  10967954   \n",
       " 503  https://datos.madrid.es/egob/kos/entidadesYorg...  10967959   \n",
       " \n",
       "                                                  title  \\\n",
       " 0    Instalación Deportiva  Básica Embalse de San Juan   \n",
       " 1         Instalación Deportiva Básica Alto del Retiro   \n",
       " 2    Instalación Deportiva Básica Avenida de Cerro ...   \n",
       " 3    Instalación Deportiva Básica Avenida de las Su...   \n",
       " 4    Instalación Deportiva Básica Avenida del Ensan...   \n",
       " ..                                                 ...   \n",
       " 499  Instalación Deportiva Municipal Rocódromo 'Roc...   \n",
       " 500  Instalación deportiva municipal básica Campo d...   \n",
       " 501                Parque Lineal UZI 0.06 Arroyofresno   \n",
       " 502                    Pista de Patinaje Paco de Lucía   \n",
       " 503      Pista de petanca Centro de Mayores La Vaguada   \n",
       " \n",
       "                                               relation  \\\n",
       " 0    http://www.madrid.es/sites/v/index.jsp?vgnextc...   \n",
       " 1    http://www.madrid.es/sites/v/index.jsp?vgnextc...   \n",
       " 2    http://www.madrid.es/sites/v/index.jsp?vgnextc...   \n",
       " 3    http://www.madrid.es/sites/v/index.jsp?vgnextc...   \n",
       " 4    http://www.madrid.es/sites/v/index.jsp?vgnextc...   \n",
       " ..                                                 ...   \n",
       " 499  http://www.madrid.es/sites/v/index.jsp?vgnextc...   \n",
       " 500  http://www.madrid.es/sites/v/index.jsp?vgnextc...   \n",
       " 501  http://www.madrid.es/sites/v/index.jsp?vgnextc...   \n",
       " 502  http://www.madrid.es/sites/v/index.jsp?vgnextc...   \n",
       " 503  http://www.madrid.es/sites/v/index.jsp?vgnextc...   \n",
       " \n",
       "                                                address  \\\n",
       " 0    {'district': {'@id': 'https://datos.madrid.es/...   \n",
       " 1    {'district': {'@id': 'https://datos.madrid.es/...   \n",
       " 2    {'district': {'@id': 'https://datos.madrid.es/...   \n",
       " 3    {'district': {'@id': 'https://datos.madrid.es/...   \n",
       " 4    {'district': {'@id': 'https://datos.madrid.es/...   \n",
       " ..                                                 ...   \n",
       " 499  {'district': {'@id': 'https://datos.madrid.es/...   \n",
       " 500  {'district': {'@id': 'https://datos.madrid.es/...   \n",
       " 501  {'district': {'@id': 'https://datos.madrid.es/...   \n",
       " 502  {'district': {'@id': 'https://datos.madrid.es/...   \n",
       " 503  {'district': {'@id': 'https://datos.madrid.es/...   \n",
       " \n",
       "                                               location  \\\n",
       " 0    {'latitude': 40.36264285659688, 'longitude': -...   \n",
       " 1    {'latitude': 40.36751469466709, 'longitude': -...   \n",
       " 2    {'latitude': 40.36861899124304, 'longitude': -...   \n",
       " 3    {'latitude': 40.370297266524084, 'longitude': ...   \n",
       " 4    {'latitude': 40.370297266524084, 'longitude': ...   \n",
       " ..                                                 ...   \n",
       " 499  {'latitude': 40.39927267070148, 'longitude': -...   \n",
       " 500  {'latitude': 40.397186411932395, 'longitude': ...   \n",
       " 501  {'latitude': 40.487146568534655, 'longitude': ...   \n",
       " 502  {'latitude': 40.38527831238433, 'longitude': -...   \n",
       " 503  {'latitude': 40.47903297218874, 'longitude': -...   \n",
       " \n",
       "                                           organization  \n",
       " 0    {'organization-desc': '  Bus: 58 , 63 , 145Ren...  \n",
       " 1    {'organization-desc': '  Metro: Las Suertes', ...  \n",
       " 2    {'organization-desc': '  Metro: CongostoBus: 1...  \n",
       " 3    {'organization-desc': '  Metro: Las Suertes', ...  \n",
       " 4    {'organization-desc': '  Metro: Las Suertes', ...  \n",
       " ..                                                 ...  \n",
       " 499  {'organization-desc': 'Escuela de Escalada  Me...  \n",
       " 500  {'organization-desc': ' Gestionado por la Inst...  \n",
       " 501  {'organization-desc': '  Metro: Antonio Machad...  \n",
       " 502  {'organization-desc': '  Metro: Antonio Machad...  \n",
       " 503  {'organization-desc': '  Metro: Antonio Machad...  \n",
       " \n",
       " [504 rows x 8 columns])"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def acquire():\n",
    "    df_bicimad = pd.read_csv(\"../data/bicimad_stations.csv\", sep=\"\\t\")\n",
    "\n",
    "    headers = {\n",
    "        'Accept': 'application/json',\n",
    "    }\n",
    "    \n",
    "    response     = requests.get('https://datos.madrid.es/egob/catalogo/200215-0-instalaciones-deportivas.json', headers=headers)\n",
    "    json_data    = response.json()\n",
    "    text         = json_data['@graph']\n",
    "    df_deportivo = pd.DataFrame(text)\n",
    "    return df_bicimad,df_deportivo \n",
    "    \n",
    "df_bicimad,df_deportivo=acquire()\n",
    "df_bicimad,df_deportivo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "955d7e53-ba45-412b-adbc-d1f2a4b49d83",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ae465a2a-e15d-407a-b97f-bae378416f9b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                             name  \\\n",
      "0           1a - Puerta del Sol A   \n",
      "1           1b - Puerta del Sol B   \n",
      "2                 2 - Miguel Moya   \n",
      "3          3 - Plaza Conde Suchil   \n",
      "4                    4 - Malasaña   \n",
      "..                            ...   \n",
      "259                    257 - INEF   \n",
      "260  258 - Ciudad Universitaria 1   \n",
      "261  259 - Ciudad Universitaria 2   \n",
      "262       260 - Facultad Biología   \n",
      "263        261 - Facultad Derecho   \n",
      "\n",
      "                                               address long_start  lat_start  \\\n",
      "0                                  Puerta del Sol nº 1  -3.701834  40.417214   \n",
      "1                                  Puerta del Sol nº 1  -3.701603  40.417313   \n",
      "2                               Calle Miguel Moya nº 1  -3.705842  40.420589   \n",
      "3             Plaza del Conde del Valle de Súchil nº 3  -3.706917  40.430294   \n",
      "4                          Calle Manuela Malasaña nº 5  -3.702587  40.428552   \n",
      "..                                                 ...        ...        ...   \n",
      "259  Avenida Juan de Herrera frente a la calle Paul...   -3.72997   40.43896   \n",
      "260  Avenida de la Complutense (Metro Ciudad Univer...   -3.72699   40.44375   \n",
      "261  Avenida de la Complutense (Metro Ciudad Univer...   -3.72693   40.44342   \n",
      "262          Calle José Antonio Novais frente al nº 12  -3.727295  40.448332   \n",
      "263                          Avenida Complutense nº 23   -3.72937   40.45109   \n",
      "\n",
      "     id  \n",
      "0     1  \n",
      "1     1  \n",
      "2     1  \n",
      "3     1  \n",
      "4     1  \n",
      "..   ..  \n",
      "259   1  \n",
      "260   1  \n",
      "261   1  \n",
      "262   1  \n",
      "263   1  \n",
      "\n",
      "[264 rows x 5 columns]                                              distrito  \\\n",
      "0                         CALLE EMBALSE DE SAN JUAN 1   \n",
      "1    CALLE ALTO DEL RETIRO 13 c/v calle Antonio Gades   \n",
      "2                              AVENIDA CERRO MILANO 1   \n",
      "3                     AVENIDA avenida de las Suertes    \n",
      "4                     AVENIDA ENSANCHE DE VALLECAS 11   \n",
      "..                                                ...   \n",
      "499                            AVENIDA MANZANARES 108   \n",
      "500                           CALLE CUART DE POBLET 6   \n",
      "501                           CALLE MARIA DE MAEZTU 1   \n",
      "502                          AUDITORIO PACO DE LUCIA    \n",
      "503                      AVENIDA MONFORTE DE LEMOS 36   \n",
      "\n",
      "                                      centro deportivo lat_finish long_finish  \\\n",
      "0    Instalación Deportiva  Básica Embalse de San Juan  40.362643   -3.598148   \n",
      "1         Instalación Deportiva Básica Alto del Retiro  40.367515   -3.588265   \n",
      "2    Instalación Deportiva Básica Avenida de Cerro ...  40.368619   -3.618357   \n",
      "3    Instalación Deportiva Básica Avenida de las Su...  40.370297   -3.612067   \n",
      "4    Instalación Deportiva Básica Avenida del Ensan...  40.370297   -3.612067   \n",
      "..                                                 ...        ...         ...   \n",
      "499  Instalación Deportiva Municipal Rocódromo 'Roc...  40.399273   -3.718824   \n",
      "500  Instalación deportiva municipal básica Campo d...  40.397186    -3.75184   \n",
      "501                Parque Lineal UZI 0.06 Arroyofresno  40.487147   -3.732863   \n",
      "502                    Pista de Patinaje Paco de Lucía  40.385278   -3.764155   \n",
      "503      Pista de petanca Centro de Mayores La Vaguada  40.479033   -3.708264   \n",
      "\n",
      "     id  \n",
      "0     1  \n",
      "1     1  \n",
      "2     1  \n",
      "3     1  \n",
      "4     1  \n",
      "..   ..  \n",
      "499   1  \n",
      "500   1  \n",
      "501   1  \n",
      "502   1  \n",
      "503   1  \n",
      "\n",
      "[504 rows x 5 columns]                           name                    address long_start  \\\n",
      "0        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
      "1        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
      "2        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
      "3        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
      "4        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
      "...                        ...                        ...        ...   \n",
      "133051  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
      "133052  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
      "133053  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
      "133054  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
      "133055  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
      "\n",
      "        lat_start                                          distrito  \\\n",
      "0       40.417214                       CALLE EMBALSE DE SAN JUAN 1   \n",
      "1       40.417214  CALLE ALTO DEL RETIRO 13 c/v calle Antonio Gades   \n",
      "2       40.417214                            AVENIDA CERRO MILANO 1   \n",
      "3       40.417214                   AVENIDA avenida de las Suertes    \n",
      "4       40.417214                   AVENIDA ENSANCHE DE VALLECAS 11   \n",
      "...           ...                                               ...   \n",
      "133051   40.45109                            AVENIDA MANZANARES 108   \n",
      "133052   40.45109                           CALLE CUART DE POBLET 6   \n",
      "133053   40.45109                           CALLE MARIA DE MAEZTU 1   \n",
      "133054   40.45109                          AUDITORIO PACO DE LUCIA    \n",
      "133055   40.45109                      AVENIDA MONFORTE DE LEMOS 36   \n",
      "\n",
      "                                         centro deportivo lat_finish  \\\n",
      "0       Instalación Deportiva  Básica Embalse de San Juan  40.362643   \n",
      "1            Instalación Deportiva Básica Alto del Retiro  40.367515   \n",
      "2       Instalación Deportiva Básica Avenida de Cerro ...  40.368619   \n",
      "3       Instalación Deportiva Básica Avenida de las Su...  40.370297   \n",
      "4       Instalación Deportiva Básica Avenida del Ensan...  40.370297   \n",
      "...                                                   ...        ...   \n",
      "133051  Instalación Deportiva Municipal Rocódromo 'Roc...  40.399273   \n",
      "133052  Instalación deportiva municipal básica Campo d...  40.397186   \n",
      "133053                Parque Lineal UZI 0.06 Arroyofresno  40.487147   \n",
      "133054                    Pista de Patinaje Paco de Lucía  40.385278   \n",
      "133055      Pista de petanca Centro de Mayores La Vaguada  40.479033   \n",
      "\n",
      "       long_finish  \n",
      "0        -3.598148  \n",
      "1        -3.588265  \n",
      "2        -3.618357  \n",
      "3        -3.612067  \n",
      "4        -3.612067  \n",
      "...            ...  \n",
      "133051   -3.718824  \n",
      "133052    -3.75184  \n",
      "133053   -3.732863  \n",
      "133054   -3.764155  \n",
      "133055   -3.708264  \n",
      "\n",
      "[133056 rows x 8 columns]\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "(                             name  \\\n",
       " 0           1a - Puerta del Sol A   \n",
       " 1           1b - Puerta del Sol B   \n",
       " 2                 2 - Miguel Moya   \n",
       " 3          3 - Plaza Conde Suchil   \n",
       " 4                    4 - Malasaña   \n",
       " ..                            ...   \n",
       " 259                    257 - INEF   \n",
       " 260  258 - Ciudad Universitaria 1   \n",
       " 261  259 - Ciudad Universitaria 2   \n",
       " 262       260 - Facultad Biología   \n",
       " 263        261 - Facultad Derecho   \n",
       " \n",
       "                                                address long_start  lat_start  \\\n",
       " 0                                  Puerta del Sol nº 1  -3.701834  40.417214   \n",
       " 1                                  Puerta del Sol nº 1  -3.701603  40.417313   \n",
       " 2                               Calle Miguel Moya nº 1  -3.705842  40.420589   \n",
       " 3             Plaza del Conde del Valle de Súchil nº 3  -3.706917  40.430294   \n",
       " 4                          Calle Manuela Malasaña nº 5  -3.702587  40.428552   \n",
       " ..                                                 ...        ...        ...   \n",
       " 259  Avenida Juan de Herrera frente a la calle Paul...   -3.72997   40.43896   \n",
       " 260  Avenida de la Complutense (Metro Ciudad Univer...   -3.72699   40.44375   \n",
       " 261  Avenida de la Complutense (Metro Ciudad Univer...   -3.72693   40.44342   \n",
       " 262          Calle José Antonio Novais frente al nº 12  -3.727295  40.448332   \n",
       " 263                          Avenida Complutense nº 23   -3.72937   40.45109   \n",
       " \n",
       "      id  \n",
       " 0     1  \n",
       " 1     1  \n",
       " 2     1  \n",
       " 3     1  \n",
       " 4     1  \n",
       " ..   ..  \n",
       " 259   1  \n",
       " 260   1  \n",
       " 261   1  \n",
       " 262   1  \n",
       " 263   1  \n",
       " \n",
       " [264 rows x 5 columns],\n",
       "                                              distrito  \\\n",
       " 0                         CALLE EMBALSE DE SAN JUAN 1   \n",
       " 1    CALLE ALTO DEL RETIRO 13 c/v calle Antonio Gades   \n",
       " 2                              AVENIDA CERRO MILANO 1   \n",
       " 3                     AVENIDA avenida de las Suertes    \n",
       " 4                     AVENIDA ENSANCHE DE VALLECAS 11   \n",
       " ..                                                ...   \n",
       " 499                            AVENIDA MANZANARES 108   \n",
       " 500                           CALLE CUART DE POBLET 6   \n",
       " 501                           CALLE MARIA DE MAEZTU 1   \n",
       " 502                          AUDITORIO PACO DE LUCIA    \n",
       " 503                      AVENIDA MONFORTE DE LEMOS 36   \n",
       " \n",
       "                                       centro deportivo lat_finish long_finish  \\\n",
       " 0    Instalación Deportiva  Básica Embalse de San Juan  40.362643   -3.598148   \n",
       " 1         Instalación Deportiva Básica Alto del Retiro  40.367515   -3.588265   \n",
       " 2    Instalación Deportiva Básica Avenida de Cerro ...  40.368619   -3.618357   \n",
       " 3    Instalación Deportiva Básica Avenida de las Su...  40.370297   -3.612067   \n",
       " 4    Instalación Deportiva Básica Avenida del Ensan...  40.370297   -3.612067   \n",
       " ..                                                 ...        ...         ...   \n",
       " 499  Instalación Deportiva Municipal Rocódromo 'Roc...  40.399273   -3.718824   \n",
       " 500  Instalación deportiva municipal básica Campo d...  40.397186    -3.75184   \n",
       " 501                Parque Lineal UZI 0.06 Arroyofresno  40.487147   -3.732863   \n",
       " 502                    Pista de Patinaje Paco de Lucía  40.385278   -3.764155   \n",
       " 503      Pista de petanca Centro de Mayores La Vaguada  40.479033   -3.708264   \n",
       " \n",
       "      id  \n",
       " 0     1  \n",
       " 1     1  \n",
       " 2     1  \n",
       " 3     1  \n",
       " 4     1  \n",
       " ..   ..  \n",
       " 499   1  \n",
       " 500   1  \n",
       " 501   1  \n",
       " 502   1  \n",
       " 503   1  \n",
       " \n",
       " [504 rows x 5 columns],\n",
       "                           name                    address long_start  \\\n",
       " 0        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
       " 1        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
       " 2        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
       " 3        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
       " 4        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
       " ...                        ...                        ...        ...   \n",
       " 133051  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
       " 133052  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
       " 133053  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
       " 133054  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
       " 133055  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
       " \n",
       "         lat_start                                          distrito  \\\n",
       " 0       40.417214                       CALLE EMBALSE DE SAN JUAN 1   \n",
       " 1       40.417214  CALLE ALTO DEL RETIRO 13 c/v calle Antonio Gades   \n",
       " 2       40.417214                            AVENIDA CERRO MILANO 1   \n",
       " 3       40.417214                   AVENIDA avenida de las Suertes    \n",
       " 4       40.417214                   AVENIDA ENSANCHE DE VALLECAS 11   \n",
       " ...           ...                                               ...   \n",
       " 133051   40.45109                            AVENIDA MANZANARES 108   \n",
       " 133052   40.45109                           CALLE CUART DE POBLET 6   \n",
       " 133053   40.45109                           CALLE MARIA DE MAEZTU 1   \n",
       " 133054   40.45109                          AUDITORIO PACO DE LUCIA    \n",
       " 133055   40.45109                      AVENIDA MONFORTE DE LEMOS 36   \n",
       " \n",
       "                                          centro deportivo lat_finish  \\\n",
       " 0       Instalación Deportiva  Básica Embalse de San Juan  40.362643   \n",
       " 1            Instalación Deportiva Básica Alto del Retiro  40.367515   \n",
       " 2       Instalación Deportiva Básica Avenida de Cerro ...  40.368619   \n",
       " 3       Instalación Deportiva Básica Avenida de las Su...  40.370297   \n",
       " 4       Instalación Deportiva Básica Avenida del Ensan...  40.370297   \n",
       " ...                                                   ...        ...   \n",
       " 133051  Instalación Deportiva Municipal Rocódromo 'Roc...  40.399273   \n",
       " 133052  Instalación deportiva municipal básica Campo d...  40.397186   \n",
       " 133053                Parque Lineal UZI 0.06 Arroyofresno  40.487147   \n",
       " 133054                    Pista de Patinaje Paco de Lucía  40.385278   \n",
       " 133055      Pista de petanca Centro de Mayores La Vaguada  40.479033   \n",
       " \n",
       "        long_finish  \n",
       " 0        -3.598148  \n",
       " 1        -3.588265  \n",
       " 2        -3.618357  \n",
       " 3        -3.612067  \n",
       " 4        -3.612067  \n",
       " ...            ...  \n",
       " 133051   -3.718824  \n",
       " 133052    -3.75184  \n",
       " 133053   -3.732863  \n",
       " 133054   -3.764155  \n",
       " 133055   -3.708264  \n",
       " \n",
       " [133056 rows x 8 columns])"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def merge_clean(df_bicim,df_centrosd):\n",
    "    df_bicim=pd.DataFrame(columns=[\"name\",\"address\",\"long_start\",\"lat_start\"]) \n",
    "    for i in range(len(df_bicimad[\"address\"])):\n",
    "        lugar=df_bicimad[\"address\"][i]\n",
    "        name=df_bicimad[\"name\"][i]\n",
    "        direccion=ast.literal_eval(df_bicimad[\"geometry.coordinates\"][i])   \n",
    "        latitude=direccion[1]\n",
    "        longitude=direccion[0]\n",
    "        df_bicim.loc[i,\"address\"]=lugar\n",
    "        df_bicim.loc[i,\"long_start\"]=longitude\n",
    "        df_bicim.loc[i,\"lat_start\"]=latitude\n",
    "        df_bicim.loc[i,\"name\"]=name\n",
    "    df_bicim[\"id\"]=1\n",
    "    \n",
    "    df_centrosd=pd.DataFrame(columns=['distrito',\"centro deportivo\",\"lat_finish\",\"long_finish\"])  \n",
    "    for i in range(len(df_deportivo[\"title\"])):\n",
    "        centro=df_deportivo[\"title\"][i]\n",
    "        direccion=df_deportivo[\"location\"][i]\n",
    "        sitio_interes=df_deportivo[\"address\"][i]\n",
    "        latitude=direccion[\"latitude\"]\n",
    "        longitude=direccion[\"longitude\"]\n",
    "        sitio_inter=sitio_interes['street-address']\n",
    "        df_centrosd.loc[i,\"centro deportivo\"]=centro\n",
    "        df_centrosd.loc[i,\"lat_finish\"]=latitude\n",
    "        df_centrosd.loc[i,\"long_finish\"]=longitude\n",
    "        df_centrosd.loc[i,'distrito']=sitio_inter\n",
    "    df_centrosd['id']= 1    \n",
    "    df_union =df_union = pd.merge(df_bicim, df_centrosd, on='id')\n",
    "    df_limpio=df_union.drop('id', axis=1)\n",
    "    return df_bicim,df_centrosd,df_limpio\n",
    "df_bicim,df_centrosd,df_limpio=merge_clean(df_bicimad,df_deportivo)\n",
    "print(df_bicim,df_centrosd,df_limpio)\n",
    "df_bicim,df_centrosd,df_limpio    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "683ae556-ca75-47b9-bf2b-7b98475870e7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name</th>\n",
       "      <th>address</th>\n",
       "      <th>long_start</th>\n",
       "      <th>lat_start</th>\n",
       "      <th>distrito</th>\n",
       "      <th>centro deportivo</th>\n",
       "      <th>lat_finish</th>\n",
       "      <th>long_finish</th>\n",
       "      <th>distancia_m</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1a - Puerta del Sol A</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>-3.701834</td>\n",
       "      <td>40.417214</td>\n",
       "      <td>CALLE EMBALSE DE SAN JUAN 1</td>\n",
       "      <td>Instalación Deportiva  Básica Embalse de San Juan</td>\n",
       "      <td>40.362643</td>\n",
       "      <td>-3.598148</td>\n",
       "      <td>13064.016996</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1a - Puerta del Sol A</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>-3.701834</td>\n",
       "      <td>40.417214</td>\n",
       "      <td>CALLE ALTO DEL RETIRO 13 c/v calle Antonio Gades</td>\n",
       "      <td>Instalación Deportiva Básica Alto del Retiro</td>\n",
       "      <td>40.367515</td>\n",
       "      <td>-3.588265</td>\n",
       "      <td>13823.514077</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1a - Puerta del Sol A</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>-3.701834</td>\n",
       "      <td>40.417214</td>\n",
       "      <td>AVENIDA CERRO MILANO 1</td>\n",
       "      <td>Instalación Deportiva Básica Avenida de Cerro ...</td>\n",
       "      <td>40.368619</td>\n",
       "      <td>-3.618357</td>\n",
       "      <td>10768.928322</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1a - Puerta del Sol A</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>-3.701834</td>\n",
       "      <td>40.417214</td>\n",
       "      <td>AVENIDA avenida de las Suertes</td>\n",
       "      <td>Instalación Deportiva Básica Avenida de las Su...</td>\n",
       "      <td>40.370297</td>\n",
       "      <td>-3.612067</td>\n",
       "      <td>11293.379626</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1a - Puerta del Sol A</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>-3.701834</td>\n",
       "      <td>40.417214</td>\n",
       "      <td>AVENIDA ENSANCHE DE VALLECAS 11</td>\n",
       "      <td>Instalación Deportiva Básica Avenida del Ensan...</td>\n",
       "      <td>40.370297</td>\n",
       "      <td>-3.612067</td>\n",
       "      <td>11293.379626</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>133051</th>\n",
       "      <td>261 - Facultad Derecho</td>\n",
       "      <td>Avenida Complutense nº 23</td>\n",
       "      <td>-3.72937</td>\n",
       "      <td>40.45109</td>\n",
       "      <td>AVENIDA MANZANARES 108</td>\n",
       "      <td>Instalación Deportiva Municipal Rocódromo 'Roc...</td>\n",
       "      <td>40.399273</td>\n",
       "      <td>-3.718824</td>\n",
       "      <td>5887.026246</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>133052</th>\n",
       "      <td>261 - Facultad Derecho</td>\n",
       "      <td>Avenida Complutense nº 23</td>\n",
       "      <td>-3.72937</td>\n",
       "      <td>40.45109</td>\n",
       "      <td>CALLE CUART DE POBLET 6</td>\n",
       "      <td>Instalación deportiva municipal básica Campo d...</td>\n",
       "      <td>40.397186</td>\n",
       "      <td>-3.75184</td>\n",
       "      <td>6503.053758</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>133053</th>\n",
       "      <td>261 - Facultad Derecho</td>\n",
       "      <td>Avenida Complutense nº 23</td>\n",
       "      <td>-3.72937</td>\n",
       "      <td>40.45109</td>\n",
       "      <td>CALLE MARIA DE MAEZTU 1</td>\n",
       "      <td>Parque Lineal UZI 0.06 Arroyofresno</td>\n",
       "      <td>40.487147</td>\n",
       "      <td>-3.732863</td>\n",
       "      <td>4032.665528</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>133054</th>\n",
       "      <td>261 - Facultad Derecho</td>\n",
       "      <td>Avenida Complutense nº 23</td>\n",
       "      <td>-3.72937</td>\n",
       "      <td>40.45109</td>\n",
       "      <td>AUDITORIO PACO DE LUCIA</td>\n",
       "      <td>Pista de Patinaje Paco de Lucía</td>\n",
       "      <td>40.385278</td>\n",
       "      <td>-3.764155</td>\n",
       "      <td>8290.409536</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>133055</th>\n",
       "      <td>261 - Facultad Derecho</td>\n",
       "      <td>Avenida Complutense nº 23</td>\n",
       "      <td>-3.72937</td>\n",
       "      <td>40.45109</td>\n",
       "      <td>AVENIDA MONFORTE DE LEMOS 36</td>\n",
       "      <td>Pista de petanca Centro de Mayores La Vaguada</td>\n",
       "      <td>40.479033</td>\n",
       "      <td>-3.708264</td>\n",
       "      <td>3901.183322</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>133056 rows × 9 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                          name                    address long_start  \\\n",
       "0        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
       "1        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
       "2        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
       "3        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
       "4        1a - Puerta del Sol A        Puerta del Sol nº 1  -3.701834   \n",
       "...                        ...                        ...        ...   \n",
       "133051  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
       "133052  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
       "133053  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
       "133054  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
       "133055  261 - Facultad Derecho  Avenida Complutense nº 23   -3.72937   \n",
       "\n",
       "        lat_start                                          distrito  \\\n",
       "0       40.417214                       CALLE EMBALSE DE SAN JUAN 1   \n",
       "1       40.417214  CALLE ALTO DEL RETIRO 13 c/v calle Antonio Gades   \n",
       "2       40.417214                            AVENIDA CERRO MILANO 1   \n",
       "3       40.417214                   AVENIDA avenida de las Suertes    \n",
       "4       40.417214                   AVENIDA ENSANCHE DE VALLECAS 11   \n",
       "...           ...                                               ...   \n",
       "133051   40.45109                            AVENIDA MANZANARES 108   \n",
       "133052   40.45109                           CALLE CUART DE POBLET 6   \n",
       "133053   40.45109                           CALLE MARIA DE MAEZTU 1   \n",
       "133054   40.45109                          AUDITORIO PACO DE LUCIA    \n",
       "133055   40.45109                      AVENIDA MONFORTE DE LEMOS 36   \n",
       "\n",
       "                                         centro deportivo lat_finish  \\\n",
       "0       Instalación Deportiva  Básica Embalse de San Juan  40.362643   \n",
       "1            Instalación Deportiva Básica Alto del Retiro  40.367515   \n",
       "2       Instalación Deportiva Básica Avenida de Cerro ...  40.368619   \n",
       "3       Instalación Deportiva Básica Avenida de las Su...  40.370297   \n",
       "4       Instalación Deportiva Básica Avenida del Ensan...  40.370297   \n",
       "...                                                   ...        ...   \n",
       "133051  Instalación Deportiva Municipal Rocódromo 'Roc...  40.399273   \n",
       "133052  Instalación deportiva municipal básica Campo d...  40.397186   \n",
       "133053                Parque Lineal UZI 0.06 Arroyofresno  40.487147   \n",
       "133054                    Pista de Patinaje Paco de Lucía  40.385278   \n",
       "133055      Pista de petanca Centro de Mayores La Vaguada  40.479033   \n",
       "\n",
       "       long_finish   distancia_m  \n",
       "0        -3.598148  13064.016996  \n",
       "1        -3.588265  13823.514077  \n",
       "2        -3.618357  10768.928322  \n",
       "3        -3.612067  11293.379626  \n",
       "4        -3.612067  11293.379626  \n",
       "...            ...           ...  \n",
       "133051   -3.718824   5887.026246  \n",
       "133052    -3.75184   6503.053758  \n",
       "133053   -3.732863   4032.665528  \n",
       "133054   -3.764155   8290.409536  \n",
       "133055   -3.708264   3901.183322  \n",
       "\n",
       "[133056 rows x 9 columns]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def distancia_min(df_limpio):\n",
    "    def to_mercator(lat, long):\n",
    "        # transform latitude/longitude data in degrees to pseudo-mercator coordinates in metres\n",
    "        c = gpd.GeoSeries([Point(lat, long)], crs=4326)\n",
    "        c = c.to_crs(3857)\n",
    "        return c\n",
    "    \n",
    "    def distance_meters(lat_start, long_start, lat_finish, long_finish):\n",
    "        # return the distance in metres between to latitude/longitude pair points in degrees \n",
    "        # (e.g.: Start Point -> 40.4400607 / -3.6425358 End Point -> 40.4234825 / -3.6292625)\n",
    "        start = to_mercator(lat_start, long_start)\n",
    "        finish = to_mercator(lat_finish, long_finish)\n",
    "        return start.distance(finish)\n",
    "        \n",
    "    df_limpio[\"distancia_m\"]=df_limpio.apply(lambda row: distance_meters(row[\"lat_start\"],row[\"long_start\"],row[\"lat_finish\"],row[\"long_finish\"]),axis=1)\n",
    "    return df_limpio\n",
    "df_limpio=distancia_min(df_limpio)\n",
    "df_limpio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "85da77ff-fa9c-4d61-84de-241e8eb5926a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>centro deportivo</th>\n",
       "      <th>min</th>\n",
       "      <th>address</th>\n",
       "      <th>distrito</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Instalación Deportiva  Básica Embalse de San Juan</td>\n",
       "      <td>5844.283277</td>\n",
       "      <td>Calle Conde Duque nº 22</td>\n",
       "      <td>CALLE EMBALSE DE SAN JUAN 1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Instalación Deportiva  Básica Embalse de San Juan</td>\n",
       "      <td>5844.283277</td>\n",
       "      <td>Plaza de Alonso Martínez nº 5</td>\n",
       "      <td>CALLE EMBALSE DE SAN JUAN 1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Instalación Deportiva Básica Camino de la Suerte</td>\n",
       "      <td>3343.315432</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>CAMINO SUERTE 25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Instalación Deportiva Básica Circuito de Autom...</td>\n",
       "      <td>3186.764529</td>\n",
       "      <td>Calle Hortaleza nº 63</td>\n",
       "      <td>CALLE NAVAMURES 2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Instalación Deportiva Básica Circuito de Autom...</td>\n",
       "      <td>3186.764529</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>CALLE NAVAMURES 2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>499</th>\n",
       "      <td>Instalación Deportiva Municipal Puente de Praga</td>\n",
       "      <td>147.195007</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>AVENIDA MANZANARES 176</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>500</th>\n",
       "      <td>Instalación Deportiva Municipal Puente de Praga</td>\n",
       "      <td>147.195007</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>AVENIDA MANZANARES 176</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>501</th>\n",
       "      <td>Instalación Deportiva Municipal Puente de Praga</td>\n",
       "      <td>147.195007</td>\n",
       "      <td>Calle Miguel Moya nº 1</td>\n",
       "      <td>AVENIDA MANZANARES 176</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>502</th>\n",
       "      <td>Parque Lineal UZI 0.06 Arroyofresno</td>\n",
       "      <td>4032.665528</td>\n",
       "      <td>Calle Hortaleza nº 63</td>\n",
       "      <td>CALLE MARIA DE MAEZTU 1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>503</th>\n",
       "      <td>Pista de petanca Centro de Mayores La Vaguada</td>\n",
       "      <td>2159.005542</td>\n",
       "      <td>Puerta del Sol nº 1</td>\n",
       "      <td>AVENIDA MONFORTE DE LEMOS 36</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>504 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                      centro deportivo          min  \\\n",
       "0    Instalación Deportiva  Básica Embalse de San Juan  5844.283277   \n",
       "1    Instalación Deportiva  Básica Embalse de San Juan  5844.283277   \n",
       "2     Instalación Deportiva Básica Camino de la Suerte  3343.315432   \n",
       "3    Instalación Deportiva Básica Circuito de Autom...  3186.764529   \n",
       "4    Instalación Deportiva Básica Circuito de Autom...  3186.764529   \n",
       "..                                                 ...          ...   \n",
       "499    Instalación Deportiva Municipal Puente de Praga   147.195007   \n",
       "500    Instalación Deportiva Municipal Puente de Praga   147.195007   \n",
       "501    Instalación Deportiva Municipal Puente de Praga   147.195007   \n",
       "502                Parque Lineal UZI 0.06 Arroyofresno  4032.665528   \n",
       "503      Pista de petanca Centro de Mayores La Vaguada  2159.005542   \n",
       "\n",
       "                           address                      distrito  \n",
       "0          Calle Conde Duque nº 22   CALLE EMBALSE DE SAN JUAN 1  \n",
       "1    Plaza de Alonso Martínez nº 5   CALLE EMBALSE DE SAN JUAN 1  \n",
       "2              Puerta del Sol nº 1              CAMINO SUERTE 25  \n",
       "3            Calle Hortaleza nº 63             CALLE NAVAMURES 2  \n",
       "4              Puerta del Sol nº 1             CALLE NAVAMURES 2  \n",
       "..                             ...                           ...  \n",
       "499            Puerta del Sol nº 1        AVENIDA MANZANARES 176  \n",
       "500            Puerta del Sol nº 1        AVENIDA MANZANARES 176  \n",
       "501         Calle Miguel Moya nº 1        AVENIDA MANZANARES 176  \n",
       "502          Calle Hortaleza nº 63       CALLE MARIA DE MAEZTU 1  \n",
       "503            Puerta del Sol nº 1  AVENIDA MONFORTE DE LEMOS 36  \n",
       "\n",
       "[504 rows x 4 columns]"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def analyze(df_final):\n",
    "    df_final=df_limpio.groupby([\"centro deportivo\"]).agg({\"distancia_m\":[\"min\"]}).reset_index()\n",
    "    df_final.columns=[\"centro deportivo\",\"min\"]\n",
    "    df_min=df_final[(\"min\")].dropna().astype(int)\n",
    "    final=df_limpio.loc[df_min]\n",
    "    df_fin=pd.merge(df_final,final[[\"centro deportivo\",\"address\",\"distrito\"]],on=\"centro deportivo\")\n",
    "    return df_fin\n",
    "df_fin=analyze(df_limpio)\n",
    "df_fin"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "661977e1-bbd3-4d04-a3c7-f529ef28c166",
   "metadata": {},
   "outputs": [],
   "source": [
    "def save_csv(df_fin):\n",
    "    df_fin.to_csv(\"../csv/direcciones.csv\",sep=';', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "f362ef2c-cb8a-46af-9a86-fe88ec13dbdf",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "usage: ipykernel_launcher.py [-h] [-u UPDATE] [-c CENTRO]\n",
      "ipykernel_launcher.py: error: unrecognized arguments: -f C:\\Users\\paul_\\AppData\\Roaming\\jupyter\\runtime\\kernel-e751b2b9-bcd4-481e-9298-9ddb96bdbce3.json\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "2",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\u001b[1;31m:\u001b[0m 2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\paul_\\miniconda3\\envs\\m1\\Lib\\site-packages\\IPython\\core\\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    "def argument_parser():\n",
    "    parser       = argparse.ArgumentParser(description= 'Closest bicimad to sports centers')\n",
    "    help_message ='You have to introduce two input. Update?: \"Y\" for yes: \"N\" for no: and \"O\" for other. Sport Center (please select \"O\" as first input)'\n",
    "    parser.add_argument('-u', '--update', help='Y/N/O')\n",
    "    parser.add_argument('-c', '--centro', type=int, help='Sports Center')\n",
    "    args = parser.parse_args()\n",
    "    return args\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "a64a4c50-acc9-4877-a2c9-44c87dea6be5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "usage: ipykernel_launcher.py [-h] [-u UPDATE] [-c CENTRO]\n",
      "ipykernel_launcher.py: error: unrecognized arguments: -f C:\\Users\\paul_\\AppData\\Roaming\\jupyter\\runtime\\kernel-e751b2b9-bcd4-481e-9298-9ddb96bdbce3.json\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "2",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\u001b[1;31m:\u001b[0m 2\n"
     ]
    }
   ],
   "source": [
    "if __name__ == '__main__':\n",
    "    if argument_parser().update == 'Y': #Actualiza el csv\n",
    "        df_bicimad,df_deportivo        = acquire()\n",
    "        df_bicim,df_centrosd,df_limpio = merge_clean(df_bicim,df_centrosd)\n",
    "        df_limpio                      = distancia_min(df_limpio)\n",
    "        df_fin                         = analyze(df_final)\n",
    "        save_csv(df_fin)\n",
    "        result                         = df_fin\n",
    "        \n",
    "    elif argument_parser().update == 'N': #No actualiza, carga el csv anterior\n",
    "        result   =  pd.read_csv(\"../csv/direcciones.csv\",sep=';', index=False)\n",
    "      \n",
    "    elif argument_parser().update == 'O': #BiciMad cercano al centro deportivo especificado\n",
    "        df_fin   =  pd.read_csv(\"../csv/direcciones.csv\",sep=';', index=False)\n",
    "        centro   = argument_parser().centro\n",
    "        result   = df_fin.loc[df_fin['centro deportivo'] == centro]\n",
    "    else:\n",
    "        result = 'FATAL ERROR...you need to select the correct method'\n",
    "    print(f'The result is => {result}')\n",
    "        \n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (m1)",
   "language": "python",
   "name": "m1"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
